travis:
  secure:
    BINSTAR_TOKEN: H+ca3lJVIRNg54PFxwh93nmGTbTB/G6vDQXMRZLE04h/KQLiogMtzkmZhJaJ8KTV2qEq2blipRzGOERAeS/hQgutO8jqN5NQZ450ZoLd3KzVKbsht/0oqoZbT0FVJozFlTBNwP6n6EN9ohFjPJxbybyaOKY/vvnl4v+d0O+S/QsoKypp19HyTWMHEfmZyKfmAtzccWNvOYlazKhPwJ16iTuDMcDdhzXFvqKktn0EHWkIvfA12+tDrssfiTI2/Fnga6cjMOSYOn9C1SN+tiIu3exYF5n2Ezu+F7X2rjlrZp+N1ap4iMW10wMlrlICeWOtmUdQWQagF79WobruacowN7wL5qxRaiZTALvi1IL5gytLkZPZyaevrHRx0jEnL7l9o2Qz/rIphpp8snpMbZvuekJamGoe1dYB5MMVWrpMw+6ffs4p3/ssmlACi7WZeYwUr/30mGmyUNitXIsMV8ffo6BbeKvjqr+YxYnzvZppjz7yGNCx1DJRuAOXPyVequHib6e8+gb+i/0e3fIo7U4gGg7FWSzRcVKgtoG4o8C05I9V3hJeQbdxhWCt7WSYujpD2QgsuOUdcEplCxqs7AYgJXGo6SVOIvxfPbxcey3S+hI1VdfvTB3Y+kyNBfkg5YKWqv2ReH6PjKY6FCE7d5nNo7PVP4evE+It8HWtdNcfazU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
